# Generated by Django 4.2.19 on 2025-02-16 04:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('luxclasses', '0001_initial'),
        ('timetablelux', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fitnesstimetable',
            name='gym_class',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fitnessclasses', to='luxclasses.fitnessclasses'),
        ),
    ]
