# Generated by Django 4.2.19 on 2025-02-16 15:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('timetablelux', '0002_fitnesstimetable_gym_class'),
    ]

    operations = [
        migrations.AddField(
            model_name='fitnesstimetable',
            name='user_bookS',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, related_name='booked_classes', to=settings.AUTH_USER_MODEL),
        ),
    ]
