# Generated by Django 4.2.19 on 2025-02-16 15:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('timetablelux', '0003_fitnesstimetable_user_books'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fitnesstimetable',
            old_name='user_bookS',
            new_name='user_books',
        ),
    ]
