# Generated by Django 4.2.19 on 2025-02-14 07:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('luxclasses', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fitnessclasses',
            old_name='auhtor',
            new_name='author',
        ),
    ]
