# Generated by Django 4.2.19 on 2025-02-15 21:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('luxclasses', '0002_rename_auhtor_fitnessclasses_author'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fitnessclasses',
            old_name='title',
            new_name='gym_class_name',
        ),
        migrations.RenameField(
            model_name='fitnessclasses',
            old_name='name',
            new_name='gym_class_name_extension',
        ),
        migrations.RenameField(
            model_name='fitnessclasses',
            old_name='author',
            new_name='gymclass_creator',
        ),
        migrations.RenameField(
            model_name='fitnessclasses',
            old_name='slug',
            new_name='short_bullets_gymclassname',
        ),
    ]
