# Generated by Django 4.2.19 on 2025-09-19 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("luxclasses", "0002_fitnessclasses_detail_filename"),
    ]

    operations = [
        migrations.AddField(
            model_name="fitnessclasses",
            name="thumb_filename",
            field=models.CharField(
                blank=True,
                help_text="e.g kettlebell-thumb.webp",
                max_length=255,
            ),
        ),
    ]
