# Generated by Django 4.2.19 on 2025-09-18 14:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("luxclasses", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ScheduledClass",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "day",
                    models.IntegerField(
                        choices=[
                            (0, "Monday"),
                            (1, "Tuesday"),
                            (2, "Wednesday"),
                            (3, "Thursday"),
                            (4, "Friday"),
                            (5, "Saturday"),
                            (6, "Sunday"),
                        ],
                        default=0,
                    ),
                ),
                (
                    "gym_class_time",
                    models.IntegerField(
                        choices=[
                            (0, "09:00 AM"),
                            (1, "09:30 AM"),
                            (2, "10:00 AM"),
                            (3, "10:30 AM"),
                            (4, "11:00 AM"),
                            (5, "11:30 AM"),
                            (6, "12:00 PM"),
                            (7, "12:30 PM"),
                            (8, "01:00 PM"),
                            (9, "01:30 PM"),
                            (10, "02:00 PM"),
                            (11, "02:30 PM"),
                            (12, "03:00 PM"),
                            (13, "03:30 PM"),
                            (14, "04:00 PM"),
                            (15, "04:30 PM"),
                            (16, "05:00 PM"),
                            (17, "05:30 PM"),
                            (18, "06:00 PM"),
                            (19, "06:30 PM"),
                            (20, "07:00 PM"),
                            (21, "07:30 PM"),
                            (22, "08:00 PM"),
                            (23, "08:30 PM"),
                            (24, "09:00 PM"),
                        ],
                        default=0,
                    ),
                ),
                (
                    "teacher",
                    models.IntegerField(
                        choices=[
                            (0, "Dan Rogers"),
                            (1, "Emily Carter"),
                            (2, "James Lee"),
                            (3, "Sophia Martinez"),
                            (4, "Michael Brown"),
                            (5, "Olivia Johnson"),
                            (6, "David Smith"),
                            (7, "Isabella Clark"),
                        ],
                        default=0,
                    ),
                ),
                (
                    "gym_class_duration",
                    models.IntegerField(
                        choices=[
                            (0, "30 Minutes"),
                            (1, "45 Minutes"),
                            (2, "50 Minutes"),
                            (3, "60 Minutes"),
                        ],
                        default=0,
                    ),
                ),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                ("updated_on", models.DateTimeField(auto_now=True)),
                (
                    "gym_class",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="gym_classes",
                        to="luxclasses.fitnessclasses",
                    ),
                ),
                (
                    "gymclass_organiser",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="gymtimetable_organiser",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["day", "gym_class_time", "created_on"],
            },
        ),
    ]
