# Generated by Django 4.2.19 on 2025-09-19 19:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("gymtimetable", "0001_initial"),
    ]

    operations = [
        migrations.RunSQL(
            sql="""
                ALTER TABLE gymtimetable_scheduledclass
                DROP COLUMN IF EXISTS gym_class_time;
            """,
            reverse_sql="""
                ALTER TABLE gymtimetable_scheduledclass
                ADD COLUMN gym_class_time time NULL;
            """,
        ),
    ]
