# Generated by Django 4.2.19 on 2025-02-17 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gymtimetable', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='luxgymtimetable',
            name='status',
            field=models.CharField(choices=[('0', 'Draft'), ('1', 'Publish')], default='1'),
        ),
    ]
