# Generated by Django 4.2.19 on 2025-07-18 13:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('luxclasses', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('gymtimetable', '0002_luxgymtimetable_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScheduledClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(choices=[('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Wednesday', 'Wednesday'), ('Thursday', 'Thursday'), ('Friday', 'Friday'), ('Saturday', 'Saturday'), ('Sunday', 'Sunday')], default='Monday')),
                ('gym_class_time', models.TimeField()),
                ('teacher', models.CharField(max_length=200)),
                ('gym_class_duration', models.CharField(max_length=100)),
                ('created_on', models.DateTimeField(auto_now=True)),
                ('gym_class', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gym_classes', to='luxclasses.fitnessclasses')),
                ('gymclass_organiser', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gymtimetable_organiser', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['day', 'gym_class_time', 'created_on'],
            },
        ),
        migrations.DeleteModel(
            name='LuxGymTimetable',
        ),
    ]
