# Generated by Django 4.2.19 on 2025-09-21 18:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("gymtimetable", "0002_drop_legacy_gym_class_time"),
    ]

    operations = [
        migrations.RunSQL(
            sql="""
                ALTER TABLE gymtimetable_scheduledclass
                ALTER COLUMN teacher TYPE integer
                USING NULLIF(teacher, '')::integer;
            """,
            reverse_sql="""
                ALTER TABLE gymtimetable_scheduledclass
                ALTER COLUMN teacher TYPE varchar(10);
            """,
        ),
    ]
