# Generated by Django 4.2.19 on 2025-08-20 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gymtimetable', '0003_scheduledclass_delete_luxgymtimetable'),
    ]

    operations = [
        migrations.AddField(
            model_name='scheduledclass',
            name='updated_on',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='scheduledclass',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='scheduledclass',
            name='day',
            field=models.IntegerField(choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')], default=0),
        ),
        migrations.AlterField(
            model_name='scheduledclass',
            name='gym_class_duration',
            field=models.IntegerField(choices=[(0, '30 Minutes'), (1, '45 Minutes'), (2, '50 Minutes'), (3, '60 Minutes')], default=0),
        ),
    ]
